return function(ANUI)
    return {
        Dark = {
            Name = "Dark",
            
            Accent = Color3.fromHex("#18181b"),
            Dialog = Color3.fromHex("#161616"),
            Outline = Color3.fromHex("#FFFFFF"),
            Text = Color3.fromHex("#FFFFFF"),
            Placeholder = Color3.fromHex("#7a7a7a"),
            Background = Color3.fromHex("#101010"),
            Button = Color3.fromHex("#52525b"),
            Icon = Color3.fromHex("#a1a1aa"),
            Toggle = Color3.fromHex("#33C759"),
            Checkbox = Color3.fromHex("#0091ff"),
        },
        Light = {
            Name = "Light",
            
            Accent = Color3.fromHex("#FFFFFF"),
            Dialog = Color3.fromHex("#f4f4f5"),
            Outline = Color3.fromHex("#09090b"),
            Text = Color3.fromHex("#000000"),
            Placeholder = Color3.fromHex("#555555"),
            Background = Color3.fromHex("#e4e4e7"),
            Button = Color3.fromHex("#18181b"),
            Icon = Color3.fromHex("#52525b"),
        },
        Rose = {
            Name = "Rose",
            
            Accent = Color3.fromHex("#be185d"),
            Dialog = Color3.fromHex("#4c0519"),
            Outline = Color3.fromHex("#fecdd3"),
            Text = Color3.fromHex("#fdf2f8"),
            Placeholder = Color3.fromHex("#d67aa6"),
            Background = Color3.fromHex("#1f0308"),
            Button = Color3.fromHex("#e11d48"),
            Icon = Color3.fromHex("#fb7185"),
        },
        Plant = {
            Name = "Plant",
            
            Accent = Color3.fromHex("#166534"),
            Dialog = Color3.fromHex("#052e16"),
            Outline = Color3.fromHex("#bbf7d0"),
            Text = Color3.fromHex("#f0fdf4"),
            Placeholder = Color3.fromHex("#4fbf7a"),
            Background = Color3.fromHex("#0a1b0f"),
            Button = Color3.fromHex("#16a34a"),
            Icon = Color3.fromHex("#4ade80"),
        },
        Red = {
            Name = "Red",
            
            Accent = Color3.fromHex("#991b1b"),
            Dialog = Color3.fromHex("#450a0a"),
            Outline = Color3.fromHex("#fecaca"),
            Text = Color3.fromHex("#fef2f2"),
            Placeholder = Color3.fromHex("#d95353"),
            Background = Color3.fromHex("#1c0606"),
            Button = Color3.fromHex("#dc2626"),
            Icon = Color3.fromHex("#ef4444"),
        },
        Indigo = {
            Name = "Indigo",
            
            Accent = Color3.fromHex("#3730a3"),
            Dialog = Color3.fromHex("#1e1b4b"),
            Outline = Color3.fromHex("#c7d2fe"),
            Text = Color3.fromHex("#f1f5f9"),
            Placeholder = Color3.fromHex("#7078d9"),
            Background = Color3.fromHex("#0f0a2e"),
            Button = Color3.fromHex("#4f46e5"),
            Icon = Color3.fromHex("#6366f1"),
        },
        Sky = {
            Name = "Sky",
            
            Accent = Color3.fromHex("#0369a1"),
            Dialog = Color3.fromHex("#0c4a6e"),
            Outline = Color3.fromHex("#bae6fd"),
            Text = Color3.fromHex("#f0f9ff"),
            Placeholder = Color3.fromHex("#4fb6d9"),
            Background = Color3.fromHex("#041f2e"),
            Button = Color3.fromHex("#0284c7"),
            Icon = Color3.fromHex("#0ea5e9"),
        },
        Violet = {
            Name = "Violet",
            
            Accent = Color3.fromHex("#6d28d9"),
            Dialog = Color3.fromHex("#3c1361"),
            Outline = Color3.fromHex("#ddd6fe"),
            Text = Color3.fromHex("#faf5ff"),
            Placeholder = Color3.fromHex("#8f7ee0"),
            Background = Color3.fromHex("#1e0a3e"),
            Button = Color3.fromHex("#7c3aed"),
            Icon = Color3.fromHex("#8b5cf6"),
        },
        Amber = {
            Name = "Amber",
            
            Accent = Color3.fromHex("#b45309"),
            Dialog = Color3.fromHex("#451a03"),
            Outline = Color3.fromHex("#fde68a"),
            Text = Color3.fromHex("#fffbeb"),
            Placeholder = Color3.fromHex("#d1a326"),
            Background = Color3.fromHex("#1c1003"),
            Button = Color3.fromHex("#d97706"),
            Icon = Color3.fromHex("#f59e0b"),
        },
        Emerald = {
            Name = "Emerald",
            
            Accent = Color3.fromHex("#047857"),
            Dialog = Color3.fromHex("#022c22"),
            Outline = Color3.fromHex("#a7f3d0"),
            Text = Color3.fromHex("#ecfdf5"),
            Placeholder = Color3.fromHex("#3fbf8f"),
            Background = Color3.fromHex("#011411"),
            Button = Color3.fromHex("#059669"),
            Icon = Color3.fromHex("#10b981"),
        },
        Midnight = {
            Name = "Midnight",
            
            Accent = Color3.fromHex("#1e3a8a"),
            Dialog = Color3.fromHex("#0c1e42"),
            Outline = Color3.fromHex("#bfdbfe"),
            Text = Color3.fromHex("#dbeafe"),
            Placeholder = Color3.fromHex("#2f74d1"),
            Background = Color3.fromHex("#0a0f1e"),
            Button = Color3.fromHex("#2563eb"),
            Icon = Color3.fromHex("#3b82f6"),
        },
        Crimson = {
            Name = "Crimson",
            
            Accent = Color3.fromHex("#b91c1c"),
            Dialog = Color3.fromHex("#450a0a"),
            Outline = Color3.fromHex("#fca5a5"),
            Text = Color3.fromHex("#fef2f2"),
            Placeholder = Color3.fromHex("#6f757b"),
            Background = Color3.fromHex("#0c0404"),
            Button = Color3.fromHex("#991b1b"),
            Icon = Color3.fromHex("#dc2626"),
        },
        MonokaiPro = {
            Name = "Monokai Pro",
            
            Accent = Color3.fromHex("#fc9867"),
            Dialog = Color3.fromHex("#1e1e1e"),
            Outline = Color3.fromHex("#78dce8"),
            Text = Color3.fromHex("#fcfcfa"),
            Placeholder = Color3.fromHex("#6f6f6f"),
            Background = Color3.fromHex("#191622"),
            Button = Color3.fromHex("#ab9df2"),
            Icon = Color3.fromHex("#a9dc76"),
        },
        CottonCandy = {
            Name = "Cotton Candy",
            
            Accent = Color3.fromHex("#ec4899"),
            Dialog = Color3.fromHex("#2d1b3d"),
            Outline = Color3.fromHex("#f9a8d4"),
            Text = Color3.fromHex("#fdf2f8"),
            Placeholder = Color3.fromHex("#8a5fd3"),
            Background = Color3.fromHex("#1a0b2e"),
            Button = Color3.fromHex("#d946ef"),
            Icon = Color3.fromHex("#06b6d4"),
        },
        Rainbow = {
            Name = "Rainbow",
            
            Accent = ANUI:Gradient({
                ["0"]   = { Color = Color3.fromHex("#00ff41"), Transparency = 0 },
                ["33"]  = { Color = Color3.fromHex("#00ffff"), Transparency = 0 },
                ["66"]  = { Color = Color3.fromHex("#0080ff"), Transparency = 0 }, 
                ["100"] = { Color = Color3.fromHex("#8000ff"), Transparency = 0 },
            }, {
                Rotation = 45,
            }),
        
            Dialog = ANUI:Gradient({
                ["0"]   = { Color = Color3.fromHex("#ff0080"), Transparency = 0 }, 
                ["25"]  = { Color = Color3.fromHex("#8000ff"), Transparency = 0 },
                ["50"]  = { Color = Color3.fromHex("#0080ff"), Transparency = 0 },
                ["75"]  = { Color = Color3.fromHex("#00ff80"), Transparency = 0 },
                ["100"] = { Color = Color3.fromHex("#ff8000"), Transparency = 0 },
            }, {
                Rotation = 135,
            }),
        
            Outline = Color3.fromHex("#ffffff"),
            Text = Color3.fromHex("#ffffff"),
        
            Placeholder = Color3.fromHex("#00ff80"),
        
            Background = ANUI:Gradient({
                ["0"]   = { Color = Color3.fromHex("#ff0040"), Transparency = 0 },
                ["20"]  = { Color = Color3.fromHex("#ff4000"), Transparency = 0 },
                ["40"]  = { Color = Color3.fromHex("#ffff00"), Transparency = 0 },
                ["60"]  = { Color = Color3.fromHex("#00ff40"), Transparency = 0 },
                ["80"]  = { Color = Color3.fromHex("#0040ff"), Transparency = 0 },
                ["100"] = { Color = Color3.fromHex("#4000ff"), Transparency = 0 },
            }, {
                Rotation = 90,
            }),
        
            Button = ANUI:Gradient({
                ["0"]   = { Color = Color3.fromHex("#ff0080"), Transparency = 0 },
                ["25"]  = { Color = Color3.fromHex("#ff8000"), Transparency = 0 },
                ["50"]  = { Color = Color3.fromHex("#ffff00"), Transparency = 0 },
                ["75"]  = { Color = Color3.fromHex("#80ff00"), Transparency = 0 },
                ["100"] = { Color = Color3.fromHex("#00ffff"), Transparency = 0 },
            }, {
                Rotation = 60,
            }),
        
            Icon = Color3.fromHex("#ffffff"),
        },
        -- THEME BARU DIMULAI DARI SINI --
        NordTheme = {
            Name = "Nord",
            
            Accent = Color3.fromHex("#88c0d0"),
            Dialog = Color3.fromHex("#3b4252"),
            Outline = Color3.fromHex("#eceff4"),
            Text = Color3.fromHex("#eceff4"),
            Placeholder = Color3.fromHex("#81a1c1"),
            Background = Color3.fromHex("#2e3440"),
            Button = Color3.fromHex("#5e81ac"),
            Icon = Color3.fromHex("#8fbcbb"),
            Toggle = Color3.fromHex("#a3be8c"),
            Checkbox = Color3.fromHex("#81a1c1"),
        },
        DraculaTheme = {
            Name = "Dracula",
            
            Accent = Color3.fromHex("#ff79c6"),
            Dialog = Color3.fromHex("#44475a"),
            Outline = Color3.fromHex("#f8f8f2"),
            Text = Color3.fromHex("#f8f8f2"),
            Placeholder = Color3.fromHex("#6272a4"),
            Background = Color3.fromHex("#282a36"),
            Button = Color3.fromHex("#bd93f9"),
            Icon = Color3.fromHex("#50fa7b"),
            Toggle = Color3.fromHex("#50fa7b"),
            Checkbox = Color3.fromHex("#8be9fd"),
        },
        TokyoNight = {
            Name = "Tokyo Night",
            
            Accent = Color3.fromHex("#7aa2f7"),
            Dialog = Color3.fromHex("#16161e"),
            Outline = Color3.fromHex("#c0caf5"),
            Text = Color3.fromHex("#c0caf5"),
            Placeholder = Color3.fromHex("#565f89"),
            Background = Color3.fromHex("#1a1b26"),
            Button = Color3.fromHex("#9ece6a"),
            Icon = Color3.fromHex("#7aa2f7"),
            Toggle = Color3.fromHex("#9ece6a"),
            Checkbox = Color3.fromHex("#7aa2f7"),
        },
        OneDark = {
            Name = "One Dark",
            
            Accent = Color3.fromHex("#61afef"),
            Dialog = Color3.fromHex("#2c323c"),
            Outline = Color3.fromHex("#abb2bf"),
            Text = Color3.fromHex("#abb2bf"),
            Placeholder = Color3.fromHex("#5c6370"),
            Background = Color3.fromHex("#1e2127"),
            Button = Color3.fromHex("#e06c75"),
            Icon = Color3.fromHex("#56b6c2"),
            Toggle = Color3.fromHex("#98c379"),
            Checkbox = Color3.fromHex("#61afef"),
        },
        Gruvbox = {
            Name = "Gruvbox",
            
            Accent = Color3.fromHex("#d65c0b"),
            Dialog = Color3.fromHex("#3c3836"),
            Outline = Color3.fromHex("#ebdbb2"),
            Text = Color3.fromHex("#ebdbb2"),
            Placeholder = Color3.fromHex("#928374"),
            Background = Color3.fromHex("#282828"),
            Button = Color3.fromHex("#b8bb26"),
            Icon = Color3.fromHex("#83a598"),
            Toggle = Color3.fromHex("#b8bb26"),
            Checkbox = Color3.fromHex("#d3869b"),
        },
        SolarizedDark = {
            Name = "Solarized Dark",
            
            Accent = Color3.fromHex("#268bd2"),
            Dialog = Color3.fromHex("#073642"),
            Outline = Color3.fromHex("#93a1a1"),
            Text = Color3.fromHex("#93a1a1"),
            Placeholder = Color3.fromHex("#586e75"),
            Background = Color3.fromHex("#002b36"),
            Button = Color3.fromHex("#2aa198"),
            Icon = Color3.fromHex("#859900"),
            Toggle = Color3.fromHex("#859900"),
            Checkbox = Color3.fromHex("#268bd2"),
        },
        MaterialDark = {
            Name = "Material Dark",
            
            Accent = Color3.fromHex("#bb86fc"),
            Dialog = Color3.fromHex("#1e1e1e"),
            Outline = Color3.fromHex("#fffbfe"),
            Text = Color3.fromHex("#e1e1e6"),
            Placeholder = Color3.fromHex("#8a8a8f"),
            Background = Color3.fromHex("#121212"),
            Button = Color3.fromHex("#6200ee"),
            Icon = Color3.fromHex("#03dac6"),
            Toggle = Color3.fromHex("#03dac6"),
            Checkbox = Color3.fromHex("#bb86fc"),
        },
        CyberpunkPink = {
            Name = "Cyberpunk Pink",
            
            Accent = Color3.fromHex("#ff006e"),
            Dialog = Color3.fromHex("#0a0012"),
            Outline = Color3.fromHex("#ffbe0b"),
            Text = Color3.fromHex("#ffffff"),
            Placeholder = Color3.fromHex("#8338ec"),
            Background = Color3.fromHex("#050008"),
            Button = Color3.fromHex("#ff006e"),
            Icon = Color3.fromHex("#ffbe0b"),
            Toggle = Color3.fromHex("#06ffa5"),
            Checkbox = Color3.fromHex("#8338ec"),
        },
        OceanBlue = {
            Name = "Ocean Blue",
            
            Accent = Color3.fromHex("#0a7ea4"),
            Dialog = Color3.fromHex("#0d2c3e"),
            Outline = Color3.fromHex("#b0e0e6"),
            Text = Color3.fromHex("#d4f1f4"),
            Placeholder = Color3.fromHex("#4a90a4"),
            Background = Color3.fromHex("#061621"),
            Button = Color3.fromHex("#1695a0"),
            Icon = Color3.fromHex("#1db5d9"),
            Toggle = Color3.fromHex("#40b5b5"),
            Checkbox = Color3.fromHex("#0a7ea4"),
        },
        NeonGreen = {
            Name = "Neon Green",
            
            Accent = Color3.fromHex("#00ff00"),
            Dialog = Color3.fromHex("#0a1f0a"),
            Outline = Color3.fromHex("#00ff00"),
            Text = Color3.fromHex("#00ff00"),
            Placeholder = Color3.fromHex("#00aa00"),
            Background = Color3.fromHex("#001a00"),
            Button = Color3.fromHex("#00dd00"),
            Icon = Color3.fromHex("#00ff00"),
            Toggle = Color3.fromHex("#00ff00"),
            Checkbox = Color3.fromHex("#00ff66"),
        },
        SoftPastel = {
            Name = "Soft Pastel",
            
            Accent = Color3.fromHex("#e0bbea"),
            Dialog = Color3.fromHex("#faf5f0"),
            Outline = Color3.fromHex("#c4b5a0"),
            Text = Color3.fromHex("#5a4a4a"),
            Placeholder = Color3.fromHex("#b8a0a0"),
            Background = Color3.fromHex("#fef9f5"),
            Button = Color3.fromHex("#d4a5d4"),
            Icon = Color3.fromHex("#c9a8c9"),
            Toggle = Color3.fromHex("#a8d4a8"),
            Checkbox = Color3.fromHex("#b8d4e0"),
        },
    }
end